### ISSUE TITLE
stuck in update loop during installation

### ISSUE THREAD

**Issue by xmoanad** [atweiden/archvault#1]
don't really know what to make of it or how to explain, something about an error with acpi. just constantly cycles through what you see in the picture until manually stopped with ctrl+c. gets through the archvault setup but can't complete the install

![Wrf5lze](https://user-images.githubusercontent.com/38971229/82772123-3ab5a380-9e0c-11ea-8894-bef7c7527c9e.jpg)

**Comment by atweiden** [comment]
Arch is a rolling release distro and there's always a possibility upstream pkg updates botch downstream installers like Archvault. For better or worse, I encounter these sorts of issues several times per year.

However, in this case, upstream has [not updated](https://www.archlinux.org/packages/community/x86_64/acpi/) the `acpi` pkg since 2020-05-06. I last tested Archvault on 2020-05-19 in VirtualBox, where it succeeded without encountering this error. Hence I don't see how our friend acpi here would be causing this issue by itself.

Did you bootstrap Archvault on a clean system? `shred -fvz -n 0 /dev/sdX` -- you will lose all your data -- could be of help. On physical hardware, if for whatever reason I cancel out of the Archvault bootstrap, I always reboot and shred the hard drive before re-attempting. Or equivalently, I delete the VM I'm testing on and then bring one up fresh.

Normally, I would spin up a VM to test Archvault right now, but I can't right now due to bandwidth considerations. Sorry for the inconvenience.

**Comment by xmoanad** [comment]
That was a good suggestion. Thankfully I have nothing important on this laptop and can continuously wipe it and reinstall :) I now receive a different style error (still involving acpi for some reason). I'll give it a go in a VM at some point to see where that leads me
![20200528_160224](https://user-images.githubusercontent.com/38971229/83190629-b8c1c500-a100-11ea-99d9-e517e414a98b.jpg)

**Comment by atweiden** [comment]
`lsblk` behavior changed upstream in latest util-linux release, botching partition indexing. Fixed in https://github.com/atweiden/archvault/commit/70403259c1eb35dda0c39a38034fea5d109c5c2a

**Comment by xmoanad** [comment]
works no problem now! thanks!
